### ISSUE TITLE
SSC precision

### ISSUE THREAD

**Issue by sgbstats** [wnarifin/wnarifin.github.io#1]
Hi,

I noticed an annoying ambiguity on your sample size calculator. Where you have the precision+/- expected, it reads as if it is asking for the width on either side of the expected value rather than the total CI width. I tested the inputs against a couple of the values in the table for Buderer and I am sure that that box is asking for the total width. I think it would be useful to make it clear what the input is, maybe CI width rather than +/-.

Hope this is useful, I think your calculator is a good resource.

**Comment by wnarifin** [comment]
Hi,

Thank you for the feedback. In the calculator, +/- stands for the precision (i.e. the distance/margin of error on either side of the estimate), i.e. CI = estimate +/- precision, where precision = z(1-alpha/2) x SE.

In Buderer, she used the term "width W" in a rather confusing way as W refers to precision. In general statistical term, width should refer to (upper CI limit - lower CI limit), i.e. 2 x precision/distance for a symmetrical distribution, while she defined length = 2 x width/precision/distance. So, for the calculator, I use W to mean precision (or width in Buderer's term), not total width (or length). The value "95% CI Width of 10%" in the titles of Table 3 and 4 should mean precision (the value +/- estimate) of 0.1, i.e. estimate +/- 0.1 given its use in the paper.

I hope that clears the confusion. Again thank you for using and testing the SSC, let me know if you have any other suggestions. 

Best regards.
